### ISSUE TITLE
Airtable Error for type table

### ISSUE THREAD

**Issue by Joecorleone** [CameronWard301/airtable#11]
Hi,
first of all thanks for providing this plugin.
For DokuWiki I am using the version Release 2020-07-29 "Hogfather".
I have installed the plugin via the Extension Manager of DokuWiki. The installed version is stated as "2021-06-06".

When I am trying to display a table with the command
`{{airtable>type: "table" | record-url: "https://airtable.com/tblXYZ/viwABC?blocks=hide" | fields: "Stage" , "Country" }}`
I get the error:
`Airtable Error: Unknown field name: ""`
However, when I am displaying just one record using
`{{airtable>type: "record" | record-url: "https://airtable.com/tblXYZ/viwABC/recUVW?blocks=hide" | fields: "Stage" , "Country" }}`
it works correctly.

Thus, the API key and base key should be configured correctly.

Does anyone have an idea what's wrong, or has anyone else seen this issue? Thanks

**Comment by CameronWard301** [comment]
I think I've found the issue @Joecorleone. I'll put it into a dev build for you to test shortly

**Comment by CameronWard301** [comment]
@Joecorleone Please can you try downloading and replacing the existing plugin with the dev branch and see if that fixes your issue?

**Comment by Joecorleone** [comment]
Wow, that's quick. Sure, I just might need a few minutes to install it manually.

**Comment by teldri** [comment]
Hi,

just tested the fix, now the error changed to:
`Airtable Error: Invalid request: parameter validation failed. Check your request data.`

**Comment by CameronWard301** [comment]
@teldri hmmm, what data are you typing into DokuWiki?

**Comment by teldri** [comment]
the same string like @Joecorleone used: `{{airtable>type: "table" | record-url: "https://airtable.com/tblXYZ/viwABC?blocks=hide" | fields: "Stage" , "Country" }}`
Just the url is anonymized..

**Comment by CameronWard301** [comment]
@teldri Maybe that's the issue, as the table and view aren't real in that example?

edit: no I am getting the same error too when only supplying the record url and fields

**Comment by Joecorleone** [comment]
@CameronWard301 Hei, sorry for the wait. Actually, @teldri is the admin of our dokuwiki and I was just trying to write an article using your plugin. So I asked him 🙈 to install the plugin manually 
Sorry, I anonymized the url, but I am using the correct url in the article.

**Comment by CameronWard301** [comment]
@Joecorleone and @teldri No worries! Please try the latest dev build, I think I've fixed it now. Please note that this plugin is in very early stages and I wouldn't recommend for production yet :)

**Comment by teldri** [comment]
@CameronWard301 I think I found the issue.  There is something in the "order" parameter of the request that does not belong there. Guess it´s the table ID

edit: oh you were faster, I´ll try it, thanks

**Comment by CameronWard301** [comment]
@teldri Yes! I think, you're right. Try it now :)

**Comment by teldri** [comment]
@CameronWard301 yes cool, now I´ts working :-D

edit: Thanks a lot for your quick response

**Comment by CameronWard301** [comment]
@teldri No worries! Glad I could help, let me know if you experience any other issues :)

**Comment by Joecorleone** [comment]
Thanks a lot for your help :-)
